### PR TITLE
Erase solitaire.rb to practice rewriting with tests.

### PR DESCRIPTION
**Pull request by pangperry**
(using commit --verbose for the first time here).

### CODE REVIEW

**Comment by adarsh** [comment]
I might consider re-naming the file to `solitaire-v1.rb` or the like to keep it around for posterity (and reference).

Other than the one comment, looks good! :+1:

**Comment by pangperry** [comment]
Thank you!

**Comment by pangperry** [comment]
This brings up the question of how to properly handle multiple commits made after submitting a pull request. 😀

**Comment by adarsh** [comment]
Good question, thanks for asking!

You squash them into one commit, rewrite the message, force push to your
branch (because you are re-writing history) and then merge.

Review this guide:
https://github.com/thoughtbot/guides/tree/master/protocol/git#merge

Also read this: https://git-scm.com/docs/git-rebase#_interactive_mode

and this:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

ap

## 

@adarshp http://www.twitter.com/adarshp
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal

**Comment by pangperry** [comment]
Thanks for the guides!

**Pull request merged**
